-- migrate:up
  CREATE TABLE IF NOT EXISTS images (
    id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id VARCHAR(26),
    url TEXT,
    is_primary boolean,

    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMP NULL,
    
    CONSTRAINT images_id_pkey PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id)
  );

-- migrate:down
  DROP TABLE IF EXISTS images;